# Generated by Django 6.1 on 2026-09-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('zip_file_name', models.CharField(max_length=255)),
                ('summary_date', models.DateField()),
                ('summary_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('calculated_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('document_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Summary',
                'verbose_name_plural': 'Summaries',
                'db_table': 'summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
