# Generated by Django 6.1 on 2026-09-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='record_type',
            field=models.CharField(default='company', max_length=20),
        ),
    ]
