# Generated by Django 4.2.30 on 2026-09-01 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_summary_company_name_summary_record_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='is_verified',
            new_name='gepco_verified',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='calculated_total',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='document_total',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='record_type',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='summary_amount',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='summary_date',
        ),
        migrations.AddField(
            model_name='summary',
            name='gepco_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='gepco_summary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='grand_total_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='grand_total_summary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='grand_total_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summary',
            name='is_fully_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summary',
            name='lesco_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='lesco_summary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='lesco_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summary',
            name='mepco_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='mepco_summary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='mepco_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summary',
            name='processing_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='summary',
            name='sepco_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='sepco_summary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='sepco_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summary',
            name='sngpl_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='sngpl_summary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='sngpl_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summary',
            name='ssgc_calculated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='ssgc_summary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='summary',
            name='ssgc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summary',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 1, 9, 40, 7, 109568)),
            preserve_default=False,
        ),
    ]
