# Generated by Django 4.2.30 on 2026-09-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_is_verified_summary_gepco_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='processing_status',
        ),
    ]
